### PR TITLE
support set max-time on cursor

### PR DESCRIPTION
**Pull request by jiacai2050**

### CODE REVIEW

**Comment by jiacai2050** [comment]
It seems Travis checks failed due to the environment

```
 The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk12" --workspace "/home/travis/.cache/install-jdk" --feature "12" --license "BCL"" failed and exited with 1 during .
```

**Comment by michaelklishin** [comment]
Yes, don't worry. I will backport to `3.5.x-stable` since master will soon enough begin adopting a completely new API.

**Comment by jiacai2050** [comment]
Thanks, ping me if new release is out.

**Comment by juvenn** [comment]
Hey @michaelklishin , any chance to cut a release? Much appreciated if so.

**Pull request merged**
